remote_theme: jekyll-theme-minimal

title: "Kaysan Merchant"
description: "This site is dedicated to the SciTech portfolio of Kaysan Merchant. Currently work in-progress to be updated with full information."
lang: "en-US"
url: "https://KaysanMerchant.github.io/"

plugins:
  - jekyll-paginate
