theme: jekyll-theme-minimal
title: Kaysan Merchant

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

collections:
  grade9:
    output: true
  grade10:
    output: true
  grade11:
    output: true
  grade12:
    output: true

markdown: kramdown
permalink: /:year/:month/:day/:title/
pagination:
  enabled: true
  collection: grade9
  per_page: 5
  sort_field: date
  sort_reverse: true
paginate_path: "/page:num/"

